### ISSUE TITLE
Could not load source file "../src/Layout.ts" in source map of "../node_modules/@solana/buffer-layout/lib/Layout.js"

### ISSUE THREAD

**Issue by jelilat** [Zebec-protocol/zebec-sdk#6]
I'm trying to connect the Zebec SDK with the frontend of my app but each time I use the parcel bundler, I keep getting this error message 

`Could not load source file "../src/Layout.ts" in source map of "../node_modules/@solana/buffer-layout/lib/Layout.js"`

**Comment by raghibislam** [comment]
Remove and pre-install.
$ npm i zebecprotocol-sdk @solana/web3.js buffer-layout @solana/spl-token
It seems due to misconfiguration of node modules while setting up the project.
